### ISSUE TITLE
Bug report: I get only a white screen no text at all

### ISSUE THREAD

**Issue by inglesuniversal** [lojjic/aframe-troika-text#36] opened 2020-11-14 17:16 UTC
Web version tested on an iPhone 8

No errors shown in the console.log

Regards

**Comment by lojjic** [comment] 2020-11-14 19:51
Thanks for the report. Can you please provide more detail?

- What do you mean by "Web version"? Do you have a testcase showing the failure?
- Does it work for you on other devices/browsers? Is the failure specific to iPhone 8 or iOS Safari in general?
- When you say "white screen", does this mean it causes the entire AFrame scene to fail? Or is it just rendering a large white object in part of the view?

**Comment by inglesuniversal** [comment] 2020-11-14 20:18
Thanks for the prompt reply

a link makes things easier.

[TEST_LINK](https://inglesuniversal.com/aframe/)

**Comment by lojjic** [comment] 2020-11-14 20:37
Your testcase has a couple issues:
1) The text's default color is white, so it's invisible against the white background color of your scene
2) You haven't positioned the text, so it's not within the camera's view.
If I change these in your testcase the text shows up for me, at least in a desktop browser.

**Comment by lojjic** [comment] 2020-11-23 16:21
@inglesuniversal Are you able to reproduce the issue after fixing your testcase?

**Comment by lojjic** [comment] 2021-02-17 19:32
Closing since it seemed to be an error in the testcase. Reopen with more info if I'm wrong.

**Closed by lojjic** 2021-02-17 19:32 UTC
